### ISSUE TITLE
Failed With Simple Harmony

### ISSUE THREAD

**Issue by turiPO-huji** [johnameyer/harmony-ts#53]
Hi, I'm trying to harmonize a few chords but I get always errors like:
"Failed rule spelling on constraint <[0-9]>"
The chords should be harmonizable, so I wonder if I miss anything or maybe there is a bug.

```javascript
const hr = require('harmony-ts');


var bassNotesPrim = [
  'E2', 'F2', 'G2',
  'A2', 'B2', 'A2',
  'F2', 'G2', 'A2',
  'C3', 'F2'
];

var bassNotes = bassNotesPrim.map(n => new hr.AbsoluteNote(n));

bassNotes[3]._accidental = hr.Accidental.FLAT;
bassNotes[4]._accidental = hr.Accidental.FLAT;
bassNotes[5]._accidental = hr.Accidental.FLAT;
bassNotes[8]._accidental = hr.Accidental.FLAT;

var levels = [
  'V65', 'I',    'V43',
  'I6',  'V42',  'I6',
  'I',   'vii6', 'I6',
  'V',   'I'
];

var scaleNotes = hr.Scale.NaturalMinor.notes;
var scale = [hr.Key.F, hr.Scale.Quality.MINOR];

var inRomans = levels.map(le => new hr.RomanNumeral(le, scale));

var i = 0;
var con = [];
for (i = 0; i < bassNotes.length; i++) {
	con.push(new hr.IncompleteChord({voices:[undefined, undefined, undefined, bassNotes[i]], romanNumeral: inRomans[i], flags: {key: hr.Key.F}}));
}

var partWriter = new hr.PartWriter();
var results = hr.flattenResults(partWriter.voiceAll(con, scaleNotes));
var bestResult = results.next().value;

```

I try to make the first bass note natural F although it's Fm scale and the other flat according the scale.

Thanks!

**Comment by johnameyer** [comment]
Hello there! Thanks for checking out the library.

The immediate issue you're seeing 'spelling' is because vii6 (minor chord built on Eb) doesn't contain G but instead Gb and I6 (major chord built on F) doesn't contain Ab but A (and hopefully the indexes returned should align with that). You might have meant for viio6 (diminished chord built on E borrowed from major) or VII6 (major chord built on Eb) instead, and i6 (minor chord) instead of I6. You could also disable the failing rules if you did intend that (though with the spelling rule you'll probably get some weird outcomes). I could try to make error messages or documentation more clear if you think that would be useful.

As an aside, you can directly specify 'Ab2' instead of setting the accidental internal variable.

I haven't had a lot of time to add to the library recently, but please let me know if there is anything I can do to improve the experience or if you'd like to contribute.

**Comment by johnameyer** [comment]
Going to close this out since there's no problem with the library and I haven't heard back from you. Feel free to comment further on this issue or open another one.
